# Generated by Django 5.1.1 on 2024-09-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(blank=True, max_length=222, null=True)),
                ('coverImage', models.ImageField(upload_to='cover')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureImage', models.ImageField(blank=True, null=True, upload_to='feature_images/')),
                ('productImages', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
    ]
