# Generated by Django 5.1.1 on 2024-09-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageUrl', models.ImageField(upload_to='images/')),
                ('ImageName', models.CharField(blank=True, max_length=50, null=True)),
                ('ImageDescription', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeFeature',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
